<h1><?php
$this->getCatalogSession()->setMyName('This is Session');
echo $block->getCatalogSession()->getMyName();
echo "<br><br>";
echo $this->getHelloWorldTxt();
echo "<br><br>";
echo $this->getRegistry();
 
 ?></h1>


<image src="http://giadinh.mediacdn.vn/2017/photo-6-1503647402350.jpg" atl='asd'/>

<img src="<?php echo $block->getViewFileUrl('images/ngoctrinh.jpg'); ?>" alt="test" />

<br> <br> <br>
