<?php 
  $helper = $this->helper('OpenTechiz\Blog\Helper\UserInfo');
?>
<?php if($helper->isLoggedIn()): ?>
<?php $noti=$this->getNotification()?>
<div class="dropdown">
  <div class="wk-customsection"data-bind="scope: 'section'">
    <button onclick="myFunction()" class="dropbtn">
      <span data-bind="text: customsection().msg"></span> Notification(s)
    </button>
  </div>

  <div id="myDropdown" class="dropdown-content">
    <?php foreach ($noti as $item ) { ?>
         <a><?php echo $item->getContent(); ?></a>
    <?php } ?>
  </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "section": {
                        "component": "OpenTechiz_Blog/js/section"
                    }
                }
            }
        }
    }
</script>

<script>
/* When the user clicks on the button, 
toggle between hiding and showing the dropdown content */
function myFunction() {
    document.getElementById("myDropdown").classList.toggle("show");
}

// Close the dropdown if the user clicks outside of it
window.onclick = function(event) {
  if (!event.target.matches('.dropbtn')) {

    var dropdowns = document.getElementsByClassName("dropdown-content");
    var i;
    for (i = 0; i < dropdowns.length; i++) {
      var openDropdown = dropdowns[i];
      if (openDropdown.classList.contains('show')) {
        openDropdown.classList.remove('show');
      }
    }
  }
}
</script>
<?php endif; ?>