<h1>Booking page</h1>

<form action="<?php echo $block->getFormAction() ?>" 
      id="contact-form"
      method="post"
 >
    <input name="content" type="text">
    <br><br><br><br>

    <input name="email" type="text">
    <br><br><br><br>

    <input type="submit" id="submit" value="Send Comment">
    <br><br><br><br>
    <input type="hidden" name="post_id" value="<?php echo $block->getPostID() ?>"/>
    <input type="hidden" name="user_id" value="<?php echo $block->getUserId() ?>"/>

</form>
    <p class='note'></p>
<?php 
$ajaxurl = $block->getFormAction();
?>
<script type="text/x-magento-init">
        {
            "*": {
                "OpenTechiz_Blog/js/commentajax": {
                    "AjaxUrl": "<?php echo $ajaxurl; ?>"
                }
            }
        }
</script>
